CC := gcc
CFLAGS := $(CC) -c -ansi -Wall -pedantic

objects = main.o file.o list.o error.o asm.o

assembler: $(objects)
	$(CC) -o assembler $(objects)

main.o: main.c
	$(CFLAGS) main.c

file.o: filer.c file.h
	$(CFLAGS) file.c

list.o: list.c list.h
	$(CFLAGS) list.c

error.o: error.c error.h
	$(CFLAGS) error.c

asm.o: asm.c asm.h
	$(CFLAGS) asm.c

clean:
	rm -f objects