
main.o: main.c file.h error.h
	gcc -c -ansi -Wall -pedantic main.c -o  main

file.o: file.c file.h error.h
	gcc -c -ansi -Wall -pedantic file.c -o file.o

error.o: error.c error.h
	gcc -c -ansi -Wall -pedantic error.c -o error.o